create database customer_behaviour;
SELECT USER();
ALTER USER 'root'@'localhost'
IDENTIFIED BY '123456';
FLUSH PRIVILEGES;
select * from customer;
select count(*) from customer;

## Q1. What is the total revenue generated by male vs.female customers?
select gender,sum(purchase_amount) as revenue from customer group by gender;

## Q2. Which customers used a discount but still spent more than average purchase amount?
 select customer_id,purchase_amount from customer where discount_applied = "Yes" 
 and purchase_amount>=(select Avg(purchase_amount) from customer);
 
 ## Q3. Which are top 5 products with the highest average review rating?
 select item_purchased,avg(review_rating) as "Average Product Rating"
 from customer group by item_purchased
 order by  avg(review_rating)  desc limit 5;      #"Average product rating "desc limit 5;
 
 ## Q4 Compare the average purchase amounts between Standard and Express Shipping.
 select shipping_type,
 round(avg(purchase_amount),2) from customer
 where shipping_type in ('Standard','Express') group by shipping_type;
 
 ## Q5 Do subscribed customers spend more? compare average  spend and total revenue 
 -- between subscribers and non subscribers.
 select *  from customer;
select subscription_status,count(customer_id) as total_customers,
round(avg(purchase_amount),2) as Average_spend,
round(sum(purchase_amount),2) as Total_revenue
from customer group by subscription_status order by  Total_revenue,Average_spend desc;

## Q6 Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*),2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

## Q7 segment customers into New ,Returning and loyal on their total
-- numbers of previous purchases and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
case
    when previous_purchases = 1 then "New"
    when previous_purchases  between 2 And 10 then "Returing"
    else "Loyal"
    End As customer_segment from customer) 
    select customer_segment,count(*) as "Number of Customers" from customer_type group by customer_segment;

## Q8 What are the top 3 most purchased products within each category ?
WITH product_counts AS (
    SELECt category,item_purchased,COUNT(customer_id) AS Total_orders,
	ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT category,item_purchased,Total_orders
FROM product_counts WHERE item_rank <= 3;

## Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers  from customer where previous_purchases>5
group by subscription_status;

## Q10 What is the revenue contribution of each  age group ?
select age_group,sum(purchase_amount) as total_revenue from customer group by age_group order by total_revenue desc;


